"""testing2

Revision ID: 816153957f1a
Revises: 6b5f13b07755
Create Date: 2025-09-25 14:05:40.505471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816153957f1a'
down_revision: Union[str, Sequence[str], None] = '6b5f13b07755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_two',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='alembic'
    )
    op.create_index(op.f('ix_alembic_users_two_id'), 'users_two', ['id'], unique=False, schema='alembic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alembic_users_two_id'), table_name='users_two', schema='alembic')
    op.drop_table('users_two', schema='alembic')
    # ### end Alembic commands ###
