"""testing3

Revision ID: c5bab0d00897
Revises: 816153957f1a
Create Date: 2025-09-25 14:06:18.797715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bab0d00897'
down_revision: Union[str, Sequence[str], None] = '816153957f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alembic_users_two_id'), table_name='users_two', schema='alembic')
    op.drop_table('users_two', schema='alembic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_two',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_two_pkey')),
    schema='alembic'
    )
    op.create_index(op.f('ix_alembic_users_two_id'), 'users_two', ['id'], unique=False, schema='alembic')
    # ### end Alembic commands ###
