"""testing3

Revision ID: fc50bdbb3977
Revises: c5bab0d00897
Create Date: 2025-09-25 14:12:58.909727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc50bdbb3977'
down_revision: Union[str, Sequence[str], None] = 'c5bab0d00897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['alembic.libraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alembic'
    )
    op.create_index(op.f('ix_alembic_books_id'), 'books', ['id'], unique=False, schema='alembic')
    op.create_table('book_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['alembic.books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alembic'
    )
    op.create_index(op.f('ix_alembic_book_details_id'), 'book_details', ['id'], unique=False, schema='alembic')
    op.create_foreign_key(None, 'user_book', 'books', ['book_id'], ['id'], source_schema='alembic', referent_schema='alembic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_book', schema='alembic', type_='foreignkey')
    op.drop_index(op.f('ix_alembic_book_details_id'), table_name='book_details', schema='alembic')
    op.drop_table('book_details', schema='alembic')
    op.drop_index(op.f('ix_alembic_books_id'), table_name='books', schema='alembic')
    op.drop_table('books', schema='alembic')
    # ### end Alembic commands ###
